---
title: "class_0419"
author: "Chan"
date: "2022/4/19"
output: html_document
---

```{r chapter2-1}
#math
2+2
log(1)
exp(1)
sqrt(4)
```

```{r chapter2-2}
#object
my_obj <- 48
My_obj <- 48

#character
my_obj2 <- "R is nice"
print(my_obj2)

#add
my_obj + My_obj #OK: num + num
my_obj2 + my_obj #NG: char + num

my_obj3 <- ",Hello"
my_obj2 + my_obj3 #NG: char + char

paste(my_obj2, my_obj3) #OK: char + char
```

```{r chapter2-3}
#vector
my_vec <- c(2,3,1,6,4,3,3,7)
print(my_vec)


mean(my_vec)
var(my_vec)
sd(my_vec)
length(my_vec)

my_vec2 <- c(2,3,1,6,4,3,3,7,NA)
var(my_vec2,na.rm = T)

my_seq <- 1:10 #c(1,2,3,4,5,6,7,8,9,10)
print(1:10)
my_seq2 <- seq(from=1,to=5,by=0.5)
print(my_seq2)
```

```{r chapter2-4}
print(my_vec)
my_vec[3]
val_3 <- my_vec[3]

my_vec[c(1,5,6,8)]

id <- c(1,5,6,8)
print(my_vec[id])

my_vec[my_vec > 4]

my_vec > 4
id2 <- my_vec > 4
my_vec[id2]

id3 <- my_vec < 6 & my_vec >2
my_vec[id3]

id4 <- ((my_vec >6) | (my_vec < 3))
my_vec[id4]

```

```{r chapter3-1}
num <- 2.2
char <- "hello"
logi <- TRUE #FALSE

class(num)
class(char)
class(logi)

is.numeric(char)
is.character(char)

num_char <- as.character(num)
print(num_char)
class(num_char)
```

```{r chapter3-2}
my_mat <- matrix(1:16, nrow=4, byrow=FALSE)
my_mat
print(my_mat)

my_array <- array(1:16, dim=c(2,4,2))
my_array

my_array[,,1]

rownames(my_mat) <- c("A","B","C","D")
colnames(my_mat) <- c("a","b","c","d")
my_mat

#list
list_1 <- list(c("black","yellow","orange"),
               c(TRUE, TRUE, FALSE, TRUE, FALSE, FALSE),
               matrix(1:6, nrow=3))
list_1

list_2 <- list(colours = c("black","yellow","orange"),
               evaluation = c(TRUE, TRUE, FALSE, TRUE, FALSE, FALSE),
               time = matrix(1:6),nrow =3)

list_2
list_2$colours

str(list_2) #structure

##data frames
p.height <- c(180,155,160,167,181)
p.weight <- c(65,50,52,58,70)
p.names <- c("Joanna","Charlotte","Helen","Karen","Amy")

dataf <- data.frame(height = p.height,
                    weight = p.weight,
                    names = p.names)
dataf
dim(dataf)
str(dataf)
```

```{r chapter3-3}
flower <- read.csv("~/class/l03-04/flower.csv")
str(flower)

```

```{r chapter3-4}
flower$height
summary(flower$height)

#3.4.1
flower[1,4] # pick up the element
flower[,c(1,4)] # select columns
flower[c(1,4),] # slicing rows
```

```{r tidyverse}
library(tidyverse)
flower %>% select(height)
flower %>% select(height, weight)
flower %>% select(-height, -weight)
flower_height <- flower %>% select(height)
flower_height

head(flower)
flower %>% filter(nitrogen == "high")
flower %>%
  filter(nitrogen == "high") %>%
  filter(height >13) %>%
  select(height, weight)

##問題：data.frameでどのように処理するか？
flower[flower$nitrogen == "high" & flower$height >13, c("height", "weight")]

id1 <- flower$nitrogen == "high"
id2 <- flower$height >13
id3 <- id1 & id2
flower[id3, c("height", "weight")]

height_order <- flower[order(flower$height), ]        
height_order


#add column
flower %>% mutate(height_cm = height/100)
```

```{r chapter 6-3}
#y ~ x1 + x2
#weight ~ height + leafarea

ans <- lm(weight ~ height + leafarea, data = flower)
summary(ans)

ans2 <- lm(weight~ height * leafarea, data = flower)
summary(ans2)
```


```{r chapter7}
test_func <- function(x){
  y <- x+1
  return(y)
}

test_func(2)

for(i in 1:5){
  print(i)
}
```